version: 2
jobs:
  "build-test":
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

    environment:
      - PORT: 8080
      - EG_CONFIG_DIR: /home/circleci/repo/config

    steps:
      - checkout
      - run: curl -L https://github.com/stoplightio/prism/releases/download/v2.0.16/prism_linux_amd64 -o prism && chmod +x ./prism
      - run: npm install
      - run: git clone https://vncz:$STOPLIGHT_TOKEN@git.stoplight.io/vncz/petstore.git sl
      - run:
          command: npm start
          background: true
      - run: sleep 1
      - run: ./prism conduct ./sl/tests.scenarios.yml -e host=http://localhost:$PORT

  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: git clone https://vncz:$STOPLIGHT_TOKEN@git.stoplight.io/vncz/petstore.git sl
      - run: git remote add deploy https://$GLITCH_TOKEN:@api.glitch.com/egpetstore/git
      - run: git checkout -b glitch
      - run: git push -f --set-upstream deploy glitch
      - run: node deploy.js

workflows:
  version: 2
  build:
    jobs:
      - build-test:
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
      - deploy:
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
          requires:
            - build-test
