jwtConf: &jwtConf
  issuer: express-gateway
  audience: something
  subject: somebody
  secretOrPublicKey: ssssst

http:
  port: 3000
apiEndpoints:
  internaljwt:
    path: '/internaljwt'
  externaljwt:
    path: '/externaljwt'
serviceEndpoints:
  backend:
    url: 'http://httpbin.org'
policies:
  - proxy
  - jwt
  - oauth2
pipelines:
  internaljwt:
    apiEndpoints:
      - internaljwt
    policies:
      - oauth2:
          action:
            jwt: *jwtConf
      - proxy: &backend
          action:
            serviceEndpoint: backend
  externaljwt:
    apiEndpoints:
      - externaljwt
    policies:
      - jwt:
          action:
            checkCredentialExistence: false
            secretOrPublicKeyFile: '/app/key.pem'

      - proxy: *backend
