http:
  port: 3000
apiEndpoints:
  api:
    host: '*'
serviceEndpoints:
  backend:
    url: 'http://httpbin.org'
policies:
  - proxy
  - jwt
  - oauth2
pipelines:
  api:
    apiEndpoints:
      - api
    policies:
      - oauth2:
          action:
            jwt:
              issuer: express-gateway
              audience: something
              subject: somebody
              secretOrPublicKey: ssssst
              checkCredentialExistence: false            
      - proxy:
          action:
            serviceEndpoint: backend
