http:
  port: ${PORT}
admin:
  port: 9876
apiEndpoints:
  pets:
    path: '/pets'
  petFood:
    path: '/petFood'
  admin:
    path: '/admin*'
serviceEndpoints:
  backend:
    url: ${URL}
  admin:
    url: http://localhost:9876
policies:
  - proxy
  - key-auth
  - basic-auth
  - terminate
pipelines:
  pets:
    apiEndpoints:
      - pets
    policies:
      - terminate:
        - condition:
            name: allOf
            conditions:
              - name: method
                methods: POST
              - name: not
                condition:
                  name: json-schema
                  schema:
                    $id: 'pet'
                    type: object
                    properties:
                      name:
                        type: string
                      type:
                        type: string
                        enum:
                          - dog
                          - cat
                      favoriteFood:
                        type: string
                    required:
                      - name
                      - type
                      - favoriteFood
      - proxy:
        - action:
            serviceEndpoint: backend
  petFood:
    apiEndpoints:
      - petFood
    policies:
      - terminate:
        - condition:
            name: allOf
            conditions:
              - name: method
                methods: POST

              - name: not
                condition:
                  name: json-schema
                  schema:
                    $id: 'food'
                    type: object
                    properties:
                      name:
                        type: string
                      brand:
                        type: string
                    required:
                      - name
                      - brand
      - proxy:
        - action:
            serviceEndpoint: backend
  admin:
    apiEndpoints:
      - admin
    policies:
      - proxy:
        - action:
            serviceEndpoint: admin
            stripPath: true
