jwtConf: &jwtConf
  issuer: express-gateway
  audience: something
  subject: somebody
  secretOrPublicKey: ssssst

http:
  port: 3000

apiEndpoints:
  internaljwt:
    host: '*'
    paths: ['/internaljwt', '/internaljwt/*']
  externaljwt:
    host: '*'
    paths: ['/externaljwt', '/externaljwt/*']
serviceEndpoints:
  backend:
    url: 'https://google.es'
policies:
  - proxy
  - jwt
  - oauth2
pipelines:
  internaljwt:
    apiEndpoints:
      - internaljwt
    policies:
      - oauth2:
          action:
            jwt: *jwtConf
      - proxy: &httpBinConf
          action:
            serviceEndpoint: backend
            changeOrigin: false
            proxyOptions:
              prependPath: false
              ignorePath: true
              secure: false
  externaljwt:
    apiEndpoints:
      - externaljwt
    policies:
      - jwt:
          action:
            checkCredentialExistence: false
            secretOrPublicKeyFile: '/app/key.pem'

      - proxy: *httpBinConf
