jwtConf: &jwtConf
  - action:
      secretOrPubKey: 'superSecretString'
      checkCredentialExistence: false
http:
  port: 3000
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: '*'
serviceEndpoints:
  backend:
    url: 'http://httpbin.org'
policies:
  - proxy
  - jwt
pipelines:
  adminAPI:
    apiEndpoints:
      - api
    policies:
      - jwt: *jwtConf
      - proxy:
          - action:
              serviceEndpoint: backend
