http:
  port: ${PORT}
apiEndpoints:
  pets:
    paths: ['/pets']
  petFood:
    paths: ['/petFood']
serviceEndpoints:
  backend:
    url: ${URL}
policies:
  - proxy
  - key-auth
  - basic-auth
pipelines:
  pets:
    apiEndpoints:
      - pets
    policies:
      - proxy:
        - action:
            serviceEndpoint: backend
