http:
  port: ${PORT}
admin:
  port: 9876
apiEndpoints:
  createPet:
    path: /pets
    methods:
      - POST
  pets:
    path: /pets
  createPetFood:
    path: /petFood
    methods:
      - POST
  petFood:
    path: /petFood
  admin:
    path: /admin*
serviceEndpoints:
  backend:
    url: ${URL}
  admin:
    url: 'http://localhost:9876'
policies:
  - proxy
  - cors
  - jwt
  - terminate
pipelines:
  createPet:
    apiEndpoints:
      - createPet
    policies:
      - cors:
      - jwt:
        - action:
            checkCredentialExistence: false
            secretOrPublicKeyFile: "/app/config/cert.pem"
            audience: 'https://api.apitest.lan'
      - proxy:
          - action:
              serviceEndpoint: backend
            condition:
              name: json-schema
              logErrors: true
              schema:
                $id: pet
                type: object
                properties:
                  name:
                    type: string
                    minLength: 1
                  type:
                    type: string
                    enum:
                      - dog
                      - cat
                  favoriteFood:
                    type: string
                    minLength: 1
                required:
                  - name
                  - type
      - terminate:
          - action:
              statusCode: 422
  pets:
    apiEndpoints:
      - pets
    policies:
      - cors:
      - proxy:
          - action:
              serviceEndpoint: backend
  createPetFood:
    apiEndpoints:
      - createPetFood
    policies:
      - cors:
      - proxy:
          - action:
              serviceEndpoint: backend
            condition:
              name: json-schema
              logErrors: true
              schema:
                $id: petFood
                type: object
                properties:
                  name:
                    type: string
                    minLength: 1
                  brand:
                    type: string
                    minLength: 1
                required:
                  - name
                  - brand
      - terminate:
          - action:
              statusCode: 422
  petFood:
    apiEndpoints:
      - petFood
    policies:
      - cors:
      - proxy:
          - action:
              serviceEndpoint: backend
  admin:
    apiEndpoints:
      - admin
    policies:
      - cors:
      - proxy:
          - action:
              serviceEndpoint: admin
              stripPath: true
