jwtConf: &jwtConf
  issuer: express-gateway
  audience: something
  subject: somebody
  secretOrPublicKey: ssssst

http:
  port: 3000
apiEndpoints:
  internaljwt:
    host: '*'
    path: /internaljwt
  externaljwt:
    host: '*'
    path: /externaljwt
serviceEndpoints:
  backend:
    url: 'http://httpbin.org/ip'
policies:
  - proxy
  - jwt
  - oauth2
pipelines:
  internaljwt:
    apiEndpoints:
      - internaljwt
    policies:
      - oauth2:
          action:
            jwt: *jwtConf
      - proxy: &backend
          action:
            serviceEndpoint: backend
            changeOrigin: false
  externaljwt:
    apiEndpoints:
      - externaljwt
    policies:
      - jwt:
          action:
            checkCredentialExistence: false
            secretOrPublicKeyFile: '/Users/vincenzochianese/dev/express-gateway/lib/config/key.pem'

      - proxy: *backend
