jwtConf: &jwtConf
  issuer: express-gateway
  audience: something
  subject: somebody
  secretOrPublicKey: ssssst

http:
  port: 3000
apiEndpoints:
  internaljwt:
    path: '/internaljwt'
  externaljwt:
    path: '/externaljwt'
serviceEndpoints:
  backend:
    url: 'http://httpbin.org'
policies:
  - proxy
  - jwt
  - oauth2
pipelines:
  internaljwt:
    apiEndpoints:
      - internaljwt
    policies:
      - oauth2:
          action:
            jwt: *jwtConf
      - proxy: &backend
          action:
            serviceEndpoint: backend
  externaljwt:
    apiEndpoints:
      - externaljwt
    policies:
      - jwt:
          action:
            checkCredentialExistence: false
            secretOrPublicKey: > 
              -----BEGIN CERTIFICATE-----
              MIIC+zCCAeOgAwIBAgIJB88ZNJSDTWt/MA0GCSqGSIb3DQEBCwUAMBsxGTAXBgNV
              BAMTEGZldGlzaC5hdXRoMC5jb20wHhcNMTcxMTIzMTA1NDI0WhcNMzEwODAyMTA1
              NDI0WjAbMRkwFwYDVQQDExBmZXRpc2guYXV0aDAuY29tMIIBIjANBgkqhkiG9w0B
              AQEFAAOCAQ8AMIIBCgKCAQEAwPafVFEOZC0/QQwMgTxfLM3BzgntqD250cJvgRDh
              zkYXmxh1fGiGofHbuCC2r79nR0V4WZmehPdSWI/FEc6zyA4EisPixyGOMoQC6z6O
              +Kk7rgN0dQ3V0WpQT7XjUu5BLhtYGcyv1EcFLjT3iOOEWL0ZOndbIrEpV/7o9Sz9
              L94xIc8K+bLLqEkKEECvEHb6N4WpSnXB2t3UI6NxeJn4IZufm94Ml2XfTAQfjxe7
              96T0RAQxP9YkhbGj480HfBXenLLFhQ1ODV1hItcCNfTGEm+WN7PKYgilbNmwqSI9
              W+gktVX9aAz5+GDhtLzuwj0GsVSfoiI6c9joJWF1TRYkYwIDAQABo0IwQDAPBgNV
              HRMBAf8EBTADAQH/MB0GA1UdDgQWBBSphvhlnKXZzrpuTSI631uFSv2RxzAOBgNV
              HQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEBAJ/M9JsnsntROjJHASaKMUUV
              JqxeYXV7hc7szFjagHlsRQxWDT3W4DpTuvZ5FsMb46s0kWYZx+L8lMqye/VriIKX
              6SM2seUf0X8+7oDI2OUJF+COz4ydWlrbFp0zYROtSqi5WHudA0wB481eLSjy6WNk
              Mo+84bxTUmV2yOPQEKVlNPIOECEXhs+hmEHGSJxdefyT6WLdrEu//E2ucNtG9hBc
              b55CFKbEreLIf8Ug8uGICd2dFbJDHyeIEbo2M+4ycqMjjkWVldWIKPUrlTgxPJxb
              iK9ry6vH2U6SS8QNEkge7zsyLM85dTw7jLcAXdP4pBxXNaDPQt+ASIENPJGSqYA=
              -----END CERTIFICATE-----

      - proxy: *backend
