http:
  port: ${PORT}
admin:
  port: 9876
apiEndpoints:
  createPet:
    path: '/pets'
    methods:
      - POST
  pets:
    path: '/pets'
  createPetFood:
    path: '/petFood'
    methods:
      - POST
  petFood:
    path: '/petFood'
  admin:
    path: '/admin*'
serviceEndpoints:
  backend:
    url: ${URL}
  admin:
    url: http://localhost:9876
policies:
  - proxy
  - key-auth
  - terminate
pipelines:
  createPet:
    apiEndpoints:
      - createPet
    policies:
      - proxy:
        - action:
            serviceEndpoint: backend
          condition:
            name: json-schema
            logErrors: true
            schema:
              $id: 'pet'
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                  enum:
                    - dog
                    - cat
                favoriteFood:
                  type: string
              required:
                - name
                - type
                - favoriteFood
      - terminate:
          - action:
              statusCode: 422  
  pets:
    apiEndpoints:
      - pets
    policies:
      - proxy:
        - action:
            serviceEndpoint: backend
  createPetFood:
    apiEndpoints:
      - createPetFood
    policies:
      - proxy:
        - action:
            serviceEndpoint: backend
          condition:
            name: json-schema
            logErrors: true
            schema:
              $id: 'petFood'
              type: object
              properties:
                name:
                  type: string
                brand:
                  type: string
              required:
                - name
                - brand
      - terminate:
          - action:
              statusCode: 422
  petFood:
    apiEndpoints:
      - petFood
    policies:
      - proxy:
        - action:
            serviceEndpoint: backend
  admin:
    apiEndpoints:
      - admin
    policies:
      - proxy:
        - action:
            serviceEndpoint: admin
            stripPath: true
