jwtConf: &jwtConf
  issuer: express-gateway
  audience: something
  subject: somebody
  secretOrPublicKey: ssssst

http:
  port: 3000
admin:
  port: 9876
apiEndpoints:
  internaljwt:
    host: '*'
    paths: ['/internaljwt', '/internaljwt/*']
  externaljwt:
    host: '*'
    paths: ['/externaljwt', '/externaljwt/*']
  admin:
    host: '*'
    paths: ['/admin', '/admin/*']
serviceEndpoints:
  backend:
    url: 'http://httpbin.org'
  admin:
    url: 'http://localhost:9876'
policies:
  - proxy
  - jwt
  - oauth2
pipelines:
  admin:
    apiEndpoints:
      - admin
    policies:
      - proxy:
          action:
            serviceEndpoint: admin
            changeOrigin: false
  internaljwt:
    apiEndpoints:
      - internaljwt
    policies:
      - oauth2:
          action:
            jwt: *jwtConf
      - proxy: &backend
          action:
            serviceEndpoint: backend
            changeOrigin: false
  externaljwt:
    apiEndpoints:
      - externaljwt
    policies:
      - jwt:
          action:
            checkCredentialExistence: false
            secretOrPublicKeyFile: '/app/key.pem'

      - proxy: *backend
