http:
  port: ${PORT:-8080}
apiEndpoints:
  verticals:
    path: '/stop'
policies:
  - proxy
  - terminate
pipelines:
  common:
    apiEndpoints:
      - verticals
    policies:
      - terminate:
          - action:
              statusCode: ${STATUS_CODE:-404}
              message: 'There you are'