jwtConf: &jwtConf
  issuer: 'express-gateway'
  audience: 'something'
  subject: 'somebody'
  secretOrPublicKey: 'ssssst'
  checkCredentialExistence: false
  
http:
  port: 3000
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    paths: '/data'
  admin:
    path: '/admin'
serviceEndpoints:
  backend:
    url: 'http://httpbin.org'
  admin:
    url: 'http://localhost:9876'
    
policies:
  - proxy
  - jwt
  - oauth2
pipelines:
  adminAPI:
    apiEndpoints:
      - admin
    policies:
      - proxy:
          - action:
              serviceEndpoint: admin
  api:
    apiEndpoints:
      - api
    policies:
      - oauth2:
        - action:
            jwt: *jwtConf
      - proxy:
          - action:
              serviceEndpoint: backend
