http:
  port: ${PORT}
admin:
  port: 9876
apiEndpoints:
  pets:
    paths: ['/pets']
  petFood:
    paths: ['/petFood']
  admin:
    paths: ['/admin*']
serviceEndpoints:
  backend:
    url: ${URL}
  admin:
    url: http://localhost:9876
policies:
  - proxy
  - key-auth
  - basic-auth
pipelines:
  pets:
    apiEndpoints:
      - pets
    policies:
      - proxy:
        - action:
            serviceEndpoint: backend
  petFood:
    apiEndpoints:
      - petFood
    policies:
      - proxy:
        - action:
            serviceEndpoint: backend
  admin:
    apiEndpoints:
      - admin
    policies:
      - proxy:
        - action:
            serviceEndpoint: admin
            stripPath: true
