jwtConf: &jwtConf
  - action: *jwtConf
      secretOrPubKey: 'superSecretString'
      checkCredentialExistence: false

http:
  port: 3000
# https:
#   port: 9999
#   tls: {}
admin: # remove this section to disable admin API
  port: 9876
  hostname: localhost # use 0.0.0.0 to listen on all IPv4 interfaces 
apiEndpoints:
  api:
    host: '*'
serviceEndpoints:
  backend:
    url: 'http://httpbin.org'
policies:
  - proxy
  - jwt
pipelines:
  adminAPI:
    apiEndpoints:
      - api
    policies:
      - jwt: *jwtConf
      - proxy:
          - action:
              serviceEndpoint: backend
